- .github/workflows/rust.yml
- .github/workflows/security_audit.yml
- README.md
- src/sources/gdac.rs
> .github: Initial GitHub Actions config

- src/error.rs
- src/sources.rs
- src/sources/coinone.rs
- src/sources/gdac.rs
API docs: https://doc.coinone.co.kr/
> Initial Coinone Source

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/sources.rs
- src/sources/coinone.rs
- src/sources/gdac.rs
...based on `rust_decimal`:
https://github.com/paupino/rust-decimal
> Add a Price type

- src/sources.rs
- src/sources/gopax.rs
WIP. Todo: Add Error types, fix up `trading_pairs_404()` test.
> Initial GOPAX Source

- src/networks/terra.rs
- src/networks/terra/denom.rs
- src/networks/terra/oracle.rs
- Factor types into their own modules under `terra`
- Move exchange rate calculation to `Denom`
- Use `tokio::sync::Mutex`
> terra: Refactor ExchangeRateOracle

- src/networks/terra/denom.rs
- src/networks/terra/oracle.rs
- src/sources.rs
- src/sources/gopax.rs
Initial `Denom::UKRW` computation with all terra sources. 
Test cmd: `curl --request POST http://127.0.0.1:23456/oracles/terra`
> terra: initial Denom::UKRW computation 

- src/networks/terra/denom.rs
- src/sources.rs
- src/sources/coinone.rs
- src/sources/gdac.rs
- src/sources/gopax.rs
generic functions for weighted average
> Weighted avg generics

- src/networks/terra/denom.rs
Adding support for Binance sourced denoms
> Adding Binance sourced denoms 

- Cargo.lock
- Cargo.toml
- src/networks/terra/msg.rs
- src/networks/terra/schema.toml
...instead of a hex-encoded string
> terra: serialize prevote hash as bytes

- Cargo.lock
- Cargo.toml
- src/networks/terra/oracle.rs
Refactoring exchange rate fetching to use concurrent requests instead of serial requests.
> Concurrent Price Query

- Cargo.lock
- delphi.toml.example
- src/config.rs
- src/config/network.rs
- src/config/source.rs
- src/networks/terra.rs
- src/networks/terra/denom.rs
- src/networks/terra/oracle.rs
Not exactly sure where this number comes from, but it appears to be what the other validators are doing.
> terra: add fee to oracle vote

- delphi.toml.example
- src/config.rs
- src/config/https.rs
- src/https_client.rs
- src/networks/terra/oracle.rs
- src/sources.rs
- src/sources/binance.rs
Support for configuring an outbound web proxy in delphi.toml
> https_client: proxy configuration

- src/networks/terra/oracle.rs
Incoming requests now include the `tx_commit::Response` from the previous transaction.
We can inspect this to determine if the previous transaction failed, in which case we didn't succeed in publishing a prevote. In these cases, we should skip publishing a vote, because if we do it will break DeliverTx on the next prevote.
> Handle TX broadcast failures

- src/networks/terra/denom.rs
- src/sources/binance.rs
Uses `try_join!` to concurrently fetch prices from sources.
With these changes the requests take ~500ms locally for me.
> terra/denom: fetch all sources concurrently

- src/sources/alphavantage.rs
They use a "Note" variant in this case, which can be parsed using the default serde enum representation:
https://serde.rs/enum-representations.html
> Handle Alpha Vantage errors

- Cargo.lock
- README.md
Following deps updated:
`aho-corasick` v0.7.14 -> v0.7.15
`cc` v1.0.61 -> v1.0.62
`native-tls` v0.2.4 -> v0.2.6
`security-framework` v0.4.4 -> v2.0.0
`security-framework-sys` v0.4.3 -> v2.0.0
`sha-1` v0.9.1 -> v0.9.2
`socket2` v0.3.15 -> v0.3.16
`tinyvec` v0.3.4 -> v1.0.1
`tokio` v0.2.22 -> v0.2.23
`tokio-macros` v0.2.5 -> v0.2.6
`unicode-normalization` v0.1.13 -> v0.1.14
`url` v2.1.1 -> v2.2.0
> Updated Cargo.lock & README.md

- src/currency.rs
- src/networks/terra/denom.rs
> Adding TerraEUR

- src/currency.rs
- src/networks/terra/denom.rs
Adding Thai Baht to the Terra network
> Adding TerraTHB stablecoin

- Cargo.lock
- README.md
- delphi.toml.example
- src/config/network.rs
- src/currency.rs
- src/networks/terra/denom.rs
- src/networks/terra/msg.rs
- src/sources.rs
- src/sources/bithumb.rs
- src/sources/imf_sdr.rs
Adding Buthumb source to Terra and implementing it for krw
> terra: adding Bithumb source

- Cargo.lock
- src/currency.rs
- src/networks/terra/denom.rs
Adding TerraSEK, a stablecoin pegged to the Swedish Krona
> Adding TerraSEK

- README.md
- delphi.toml.example
- src/config/source.rs
- src/networks/terra/denom.rs
- src/sources.rs
- src/sources/currencylayer.rs
Adding Currencylayer source to Terra.
> Terra: Adding Currencylayer source

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Update dependencies ([#193])
- `utwd` and `nok` denoms ([#193])
[#193]: https://github.com/iqlusioninc/delphi/pull/193
> delphi v0.0.4

- Cargo.lock
- src/currency.rs
- src/networks/terra/denom.rs
Including Terra Indonesian rupiah and Philippine peso stablecoins
> Adding Terra IDR and PHP

- CHANGELOG.md
- Cargo.toml
- README.md: fix build status badge ([#195])
- Adding Terra IDR and PHP ([#197])
[#195]: https://github.com/iqlusioninc/delphi/pull/195
[#197]: https://github.com/iqlusioninc/delphi/pull/197
> delphi v0.0.5

- src/networks/terra/proto.rs
Sourced from https://github.com/terra-money/core/blob/main/proto/terra/oracle/v1beta1/tx.proto
> Add `terra.oracle.v1beta1.tx` protobufs
